# Generated by Django 2.2.2 on 2019-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('crop_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('land_preparation', models.TextField()),
                ('seed_selection', models.TextField()),
                ('seed_sowing', models.TextField()),
                ('irrigation', models.TextField()),
                ('crop_growth', models.TextField()),
                ('fertilizing', models.TextField()),
                ('harvesting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('availability', models.IntegerField()),
                ('items_sold', models.IntegerField()),
                ('value_per_unit', models.IntegerField()),
            ],
        ),
    ]
